"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

from .inc_django._base import *  # noqa
from .inc_django.applications import *  # noqa
from .inc_django.auth import *  # noqa
from .inc_django.caches import *  # noqa
from .inc_django.db import *  # noqa
from .inc_django.i18n import *  # noqa
from .inc_django.logging import *  # noqa
from .inc_django.media import *  # noqa
from .inc_django.middleware import *  # noqa
from .inc_django.security import *  # noqa
from .inc_django.session import *  # noqa
from .inc_django.static import *  # noqa
from .inc_django.templates import *  # noqa
from .inc_other.api import *  # noqa
from .inc_other.celery import *  # noqa
from .inc_other.cors import *  # noqa
from .inc_other.debug_toolbar import *  # noqa
from .inc_other.drf import *  # noqa
from .inc_other.modeltranslation import *  # noqa
from .inc_other.rosetta import *  # noqa
from .inc_other.sentry import *  # noqa
from .inc_other.structlog import *  # noqa
from .inc_other.swagger import *  # noqa
from .inc_other.versatile_image import *  # noqa
from .inc_other.watchman import *  # noqa
